# .github/workflows/ml-pipeline-ci.yml
name: ML Pipeline CI

on:
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, master]


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 day5/演習3 \
            --count \
            --select=E9,F63,F7,F82 \
            --show-source \
            --statistics
          flake8 day5/演習3 \
            --count \
            --exit-zero \
            --max-complexity=10 \
            --max-line-length=88

      - name: Format check with black
        run: |
          black --check day5/演習3

      - name: Run date tests
        run: |
          pytest day5/演習3/tests/test_date.py -v

      - name: Run pytest enshu2
        run: |
          pytest day5/演習2/main.py -v -s
          
